//
//  PhotoRequest.swift
//  iGallery
//
//  Created by MeeraSayabu N on 07/01/24.
//

import Foundation
import NetworkKit

/// A struct representing a photo request conforming to the DataRequest protocol.
struct PhotoRequest: DataRequest {
    
    /// Headers to be sent along with the request.
    var headers: [String: String] = [:]
    
    /// Query parameters to be included in the request.
    var queryItems: [String: String] = [:]

    /// The URL for the photo request, generated by combining the base URL and path.
    var url: String {
        let baseURL: String = "https://jsonblob.com"
        let path: String = "/api/jsonBlob/1182735235283804160"
        return baseURL + path
    }
    
    /// The HTTP method used for the photo request.
    var method: HTTPMethod {
        .get
    }
    
    /// Decodes the received data into an array of Photo objects.
    /// - Parameter data: The data received from the API response.
    /// - Returns: An array of Photo objects decoded from the provided data.
    /// - Throws: An error if the decoding process encounters an issue.
    func decode(_ data: Data) throws -> [Photo] {
        let decoder = JSONDecoder()
        let response = try decoder.decode([Photo].self, from: data)
        return response
    }
}

